/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/sEIVIJfHzol
 */

export function HabitTrackerDashboard() {
  return (
    <main className="m-6">
      <div className="flex items-center justify-center h-14">
        <h1 className="text-2xl font-bold text-[#bd1e59]">
          Edgy Hygiene Tracker
        </h1>
      </div>
      <section className="mt-6 p-4 rounded-lg bg-white dark:bg-gray-800">
        <h2 className="text-xl font-bold mb-4 text-[#bd1e59]">Habits</h2>
        <ul className="space-y-2">
          <li className="flex justify-between items-center">
            <span>Brush Teeth</span>
          </li>
          <li className="flex justify-between items-center">
            <span>Shower</span>
          </li>
        </ul>
        <button className="mt-4 inline-flex items-center px-4 py-2 border border-zinc-200 border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-[#bd1e59] hover:bg-[#9e1650] dark:border-zinc-800">
          <svg
            className="w-5 h-5"
            fill="none"
            height="24"
            stroke="currentColor"
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth="2"
            viewBox="0 24"
            width="24"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path d="M5 12h14" />
            <path d="M12 5v14" />
          </svg>
          <span className="mx-2">Add New Habit</span>
        </button>
      </section>
      <div className="grid grid-cols-7 gap-6 mt-5">
        <section className="p-4 rounded-lg bg-white dark:bg-gray-800">
          <h2 className="text-xl font-bold mb-4 text-[#bd1e59]">Monday</h2>
          <ul className="space-y-2">
            <li className="flex justify-between items-center">
              <span>Brush Teeth</span>
              <input
                className="form-checkbox h-5 w-5 text-[#bd1e59]"
                type="checkbox"
              />
            </li>
            <li className="flex justify-between items-center">
              <span>Shower</span>
              <input
                className="form-checkbox h-5 w-5 text-[#bd1e59]"
                type="checkbox"
              />
            </li>
          </ul>
        </section>
        <section className="p-4 rounded-lg bg-white dark:bg-gray-800">
          <h2 className="text-xl font-bold mb-4 text-[#bd1e59]">Tuesday</h2>
          <ul className="space-y-2">
            <li className="flex justify-between items-center">
              <span>Brush Teeth</span>
              <input
                className="form-checkbox h-5 w-5 text-[#bd1e59]"
                type="checkbox"
              />
            </li>
            <li className="flex justify-between items-center">
              <span>Shower</span>
              <input
                className="form-checkbox h-5 w-5 text-[#bd1e59]"
                type="checkbox"
              />
            </li>
          </ul>
        </section>
        <section className="p-4 rounded-lg bg-white dark:bg-gray-800">
          <h2 className="text-xl font-bold mb-4 text-[#bd1e59]">Wednesday</h2>
          <ul className="space-y-2">
            <li className="flex justify-between items-center">
              <span>Brush Teeth</span>
              <input
                className="form-checkbox h-5 w-5 text-[#bd1e59]"
                type="checkbox"
              />
            </li>
            <li className="flex justify-between items-center">
              <span>Shower</span>
              <input
                className="form-checkbox h-5 w-5 text-[#bd1e59]"
                type="checkbox"
              />
            </li>
          </ul>
        </section>
        <section className="p-4 rounded-lg bg-white dark:bg-gray-800">
          <h2 className="text-xl font-bold mb-4 text-[#bd1e59]">Thursday</h2>
          <ul className="space-y-2">
            <li className="flex justify-between items-center">
              <span>Brush Teeth</span>
              <input
                className="form-checkbox h-5 w-5 text-[#bd1e59]"
                type="checkbox"
              />
            </li>
            <li className="flex justify-between items-center">
              <span>Shower</span>
              <input
                className="form-checkbox h-5 w-5 text-[#bd1e59]"
                type="checkbox"
              />
            </li>
          </ul>
        </section>
        <section className="p-4 rounded-lg bg-white dark:bg-gray-800">
          <h2 className="text-xl font-bold mb-4 text-[#bd1e59]">Friday</h2>
          <ul className="space-y-2">
            <li className="flex justify-between items-center">
              <span>Brush Teeth</span>
              <input
                className="form-checkbox h-5 w-5 text-[#bd1e59]"
                type="checkbox"
              />
            </li>
            <li className="flex justify-between items-center">
              <span>Shower</span>
              <input
                className="form-checkbox h-5 w-5 text-[#bd1e59]"
                type="checkbox"
              />
            </li>
          </ul>
        </section>
        <section className="p-4 rounded-lg bg-white dark:bg-gray-800">
          <h2 className="text-xl font-bold mb-4 text-[#bd1e59]">Saturday</h2>
          <ul className="space-y-2">
            <li className="flex justify-between items-center">
              <span>Brush Teeth</span>
              <input
                className="form-checkbox h-5 w-5 text-[#bd1e59]"
                type="checkbox"
              />
            </li>
            <li className="flex justify-between items-center">
              <span>Shower</span>
              <input
                className="form-checkbox h-5 w-5 text-[#bd1e59]"
                type="checkbox"
              />
            </li>
          </ul>
        </section>
        <section className="p-4 rounded-lg bg-white dark:bg-gray-800">
          <h2 className="text-xl font-bold mb-4 text-[#bd1e59]">Sunday</h2>
          <ul className="space-y-2">
            <li className="flex justify-between items-center">
              <span>Brush Teeth</span>
              <input
                className="form-checkbox h-5 w-5 text-[#bd1e59]"
                type="checkbox"
              />
            </li>
            <li className="flex justify-between items-center">
              <span>Shower</span>
              <input
                className="form-checkbox h-5 w-5 text-[#bd1e59]"
                type="checkbox"
              />
            </li>
          </ul>
        </section>
      </div>
      <section className="mt-6 p-4 rounded-lg bg-white dark:bg-gray-800">
        <h2 className="text-xl font-bold mb-4 text-[#bd1e59]">
          Progress Tracker
        </h2>
        <div className="h-2 bg-gray-200 rounded">
          <div className="h-2 bg-[#bd1e59] rounded w-1/2" />
        </div>
      </section>
    </main>
  );
}
